baseURL = '/blog'
publishDir = '../src/blog'
languageCode = 'en-us'
title = 'Medendi Tactus'
theme = 'pehtheme-hugo'

paginate = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Pehtheme Hugo Lite: A minimalist Hugo theme, built with TailwindCSS, for efficient performance and minimalism.'
	mainSections = 'posts'

[params.author]
	name = 'Clint'
	bio = 'A lifelong martial artist and academy owner dedicated to promoting strength, resilience, and holistic wellness'
	avatar = '/blog/images/hero-image.webp'

[menu] # Menu management
	[[menu.main]]
		name = 'Blog'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 20
	[[menu.main]]
		name = 'Categories'
		pageRef = '/categories'
		weight = 25
	[[menu.main]]
		name = 'Book Consultation'
		url = 'https://medenditactus.netlify.app/what-we-offer#contact-form'
		weight = 35

[outputs]
    home = ["HTML", "JSON", "RSS"]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]
    source = "static/images"
    target = "assets/images"
  [[module.mounts]]
    source = "static/images"
    target = "static/images"
  [[module.mounts]]
	source = "static/admin"
    target = "static/admin"

[permalinks]
	posts = "/:slug/"